/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'reenkuma' at '3/15/17 5:10 PM' with Gradle 2.13
 *
 * @author reenkuma, @date 3/15/17 5:10 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
